<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="collision_multiplier" value="1.5" />

    <xacro:property name="limit_effort" value="100" />
    <xacro:property name="limit_velocity" value="10" />

    <xacro:property name="camera_length" value="0.0635" />
    <xacro:property name="camera_height" value="0.03175" />
    <xacro:property name="camera_width" value="0.0333" />

    <xacro:property name="camera_frame_length" value="0.0254" />
    <xacro:property name="camera_frame_height" value="0.0333" />
    <xacro:property name="camera_frame_width" value="0.04445" />

    <xacro:property name="chassis_length" value="0.187" />
    <xacro:property name="chassis_height" value="0.04" />
    <xacro:property name="chassis_width" value="0.094" />

    <xacro:property name="depth_camera_length" value="0.165" />
    <xacro:property name="depth_camera_height" value="0.40" />
    <xacro:property name="depth_camera_width" value="0.48" />

    <xacro:property name="lidar_length" value="0.12954" />
    <xacro:property name="lidar_height" value="0.07874" />
    <xacro:property name="lidar_width" value="0.09906" />

    <xacro:property name="mesh_scale" value="0.001 0.001 0.001" />

    <xacro:property name="sonar_length" value="0.0254" />
    <xacro:property name="sonar_height" value="0.0254" />
    <xacro:property name="sonar_width" value="0.0508" />

    <xacro:property name="spacer_mesh_file" value="file://$(find turbopi_ros)/meshes/spacer.stl" />
    <xacro:property name="spacer_offset_front" value="-0.0203" />
    <xacro:property name="spacer_offset_rear" value="${-chassis_width + 0.0135}" />
    <xacro:property name="spacer_offset_side" value="${chassis_width/2 - 0.0138}" />
    <xacro:property name="spacer_offset_height" value="0.015" />

    <xacro:property name="wheel_gap" value="0.005" />
    <xacro:property name="wheel_length" value="0.03" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_mass" value="0.0016" />
    <xacro:property name="wheel_mesh_file" value="file://$(find turbopi_ros)/meshes/wheel.stl" />
    <xacro:property name="wheel_offset_front" value="${chassis_length/2 - 0.0305}" />
    <xacro:property name="wheel_offset_rear" value="${-chassis_length/2 + 0.0372}" />
    <xacro:property name="wheel_offset_side" value="${wheel_length/2 + chassis_width/2 + wheel_gap}" />
    <xacro:property name="wheel_zoffset" value="${chassis_height/2 + 0.0064}" />

    <link name="base_link"></link>

    <!-- Main Body/Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius + chassis_height/2 + 0.0065}" rpy="0 0 0"/>
    </joint>
    <link name="chassis">
        <collision>
            <geometry>
                <box size="${chassis_length * collision_multiplier} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="file://$(find turbopi_ros)/meshes/chassis.stl" scale="${mesh_scale}" />
            </geometry>
            <material name="white"/>
        </visual>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="spacer_1_joint" type="fixed">
        <parent link="chassis"/>
        <child link="spacer_1"/>
        <origin xyz="${spacer_offset_front} ${spacer_offset_side} ${spacer_offset_height}" rpy="0 0 0"/>
    </joint>
    <link name="spacer_1">
        <visual>
            <geometry>
                <mesh filename="${spacer_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="brass"/>
        </visual>
    </link>

    <joint name="spacer_2_joint" type="fixed">
        <parent link="chassis"/>
        <child link="spacer_2"/>
        <origin xyz="${spacer_offset_front} -${spacer_offset_side} ${spacer_offset_height}" rpy="0 0 0"/>
    </joint>
    <link name="spacer_2">
        <visual>
            <geometry>
                <mesh filename="${spacer_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="brass"/>
        </visual>
    </link>

    <joint name="spacer_3_joint" type="fixed">
        <parent link="chassis"/>
        <child link="spacer_3"/>
        <origin xyz="${spacer_offset_rear} ${spacer_offset_side} ${spacer_offset_height}" rpy="0 0 0"/>
    </joint>
    <link name="spacer_3">
        <visual>
            <geometry>
                <mesh filename="${spacer_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="brass"/>
        </visual>
    </link>

    <joint name="spacer_4_joint" type="fixed">
        <parent link="chassis"/>
        <child link="spacer_4"/>
        <origin xyz="${spacer_offset_rear} -${spacer_offset_side} ${spacer_offset_height}" rpy="0 0 0"/>
    </joint>
    <link name="spacer_4">
        <visual>
            <geometry>
                <mesh filename="${spacer_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="brass"/>
        </visual>
    </link>

    <!-- Front Left Wheel -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="front_left_wheel"/>
        <origin xyz="${wheel_offset_front} ${wheel_offset_side} -${wheel_zoffset}" rpy="${pi/2} 0 ${pi}"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Right Wheel -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="front_right_wheel"/>
        <origin xyz="${wheel_offset_front} -${wheel_offset_side} -${wheel_zoffset}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="front_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Left Wheel -->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="rear_left_wheel"/>
        <origin xyz="${wheel_offset_rear} ${wheel_offset_side} -${wheel_zoffset}" rpy="${pi/2} 0 ${pi}"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_left_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Rear Right Wheel -->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="rear_right_wheel"/>
        <origin xyz="${wheel_offset_rear} -${wheel_offset_side} -${wheel_zoffset}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
    </joint>
    <link name="rear_right_wheel">
        <collision>
            <geometry>
                <cylinder length="${wheel_length * collision_multiplier}" radius="${wheel_radius}" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="${wheel_mesh_file}" scale="${mesh_scale}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <xacro:macro name="style" params="use_style">
        <xacro:if value="${use_style == 'default'}">
            <!-- Camera frame turns left/right -->
            <joint name="camera_frame_joint" type="revolute">
                <parent link="chassis"/>
                <child link="camera_frame"/>
                <origin xyz="${chassis_length/2 - 0.054} 0 ${chassis_height + 0.01}" rpy="0 0 0"/>
                <limit lower="-1"  upper="1"  velocity="0.1"  effort="${limit_effort}"  />
                <axis xyz="0 0 1"/>
            </joint>
            <link name="camera_frame">
                <collision>
                    <geometry>
                        <box size="${camera_frame_length} ${camera_frame_width} ${camera_frame_height}"/>
                    </geometry>
                </collision>
                <visual>
                    <geometry>
                        <mesh filename="file://$(find turbopi_ros)/meshes/camera_frame.stl" scale="${mesh_scale}" />
                    </geometry>
                    <material name="white"/>
                </visual>
                <xacro:inertial_box mass="0.01" x="${camera_frame_length}" y="${camera_frame_width}" z="${camera_frame_height}">
                    <origin xyz="0 0 ${camera_frame_height/2}" rpy="0 0 0"/>
                </xacro:inertial_box>
            </link>

            <!-- Camera angles up/down -->
            <joint name="camera_joint" type="revolute">
                <parent link="camera_frame"/>
                <child link="camera"/>
                <origin xyz="0.015 0 ${camera_frame_height * 0.4}" rpy="0 0 0"/>
                <limit lower="-0.5"  upper="1"  velocity="0.1"  effort="${limit_effort}"  />
                <axis xyz="0 1 0"/>
            </joint>
            <link name="camera">
                <collision>
                    <geometry>
                        <box size="${camera_length} ${camera_width} ${camera_height}"/>
                    </geometry>
                </collision>
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="file://$(find turbopi_ros)/meshes/camera.stl" scale="${mesh_scale}" />
                    </geometry>
                    <material name="white"/>
                </visual>
                <xacro:inertial_box mass="0.01" x="${camera_length}" y="${camera_width}" z="${camera_height}">
                    <origin xyz="0 0 ${camera_height/2}" rpy="0 0 0"/>
                </xacro:inertial_box>
            </link>
        </xacro:if>

        <xacro:if value="${use_style == 'depth'}">
            <!-- 3D Depth Camera -->
            <joint name="depth_camera_joint" type="fixed">
                <parent link="chassis"/>
                <child link="depth_camera"/>
                <axis xyz="0 0 1"/>
                <origin xyz="${chassis_length/2 - 0.054} 0 ${chassis_height}" rpy="0 0 0"/>
            </joint>
            <link name="depth_camera">
                <!-- Causes floating? -->
                <!-- <collision>
                    <geometry>
                        <box size="${depth_camera_length} ${depth_camera_width} ${depth_camera_height}"/>
                    </geometry>
                </collision> -->
                <visual>
                    <geometry>
                        <mesh filename="file://$(find turbopi_ros)/meshes/astra_s_depth_camera.stl" scale="${mesh_scale}" />
                    </geometry>
                    <material name="white"/>
                </visual>
                <xacro:inertial_box mass="0.02" x="${depth_camera_length}" y="${depth_camera_width}" z="${depth_camera_height}">
                    <origin xyz="0 0 ${depth_camera_height/2}" rpy="0 0 0"/>
                </xacro:inertial_box>
            </link>
        </xacro:if>

    </xacro:macro>

    <!-- Sonar -->
    <joint name="sonar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="sonar"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${chassis_length/2 - sonar_length*0.8} 0 ${sonar_height/5}" rpy="0 0 0"/>
    </joint>
    <link name="sonar">
        <collision>
            <geometry>
                <box size="${sonar_length} ${sonar_width} ${sonar_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find turbopi_ros)/meshes/sonar.stl" scale="${mesh_scale}" />
            </geometry>
            <material name="white"/>
        </visual>
        <xacro:inertial_box mass="0.01" x="${sonar_length}" y="${sonar_width}" z="${sonar_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- 360 Lidar -->
    <joint name="lidar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${-lidar_length/2 + 0.01} 0 0.0725" rpy="0 0 0"/>
    </joint>
    <link name="lidar">
        <collision>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <mesh filename="file://$(find turbopi_ros)/meshes/rplidar.dae" scale="1 1 1" />
            </geometry>
            <material name="black"/>
        </visual>
        <xacro:inertial_box mass="0.01" x="${lidar_length}" y="${lidar_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>
