/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.01
    angle_max: 1.5708
    angle_min: -1.5708
    # angle_max: 3.14
    # angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 2.0
    min_height: -1.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 12.0
    range_min: 0.3
    scan_time: 0.3333
    target_frame: turbopi/base_link/lidar_sensor
    transform_tolerance: 0.01
    use_inf: false
    use_sim_time: true
