controller_manager:
  ros__parameters:
    update_rate: 10

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    position_controllers:
      type: position_controllers/JointGroupPositionController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheels_per_side: 2
    wheel_separation: 1.0 # 0.192
    wheel_radius: 0.0325

    odom_frame_id: odom
    base_frame_id: base_link

    enable_odom_tf: true

    use_stamped_vel: false

mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 0.0

    front_left_wheel_command_joint_name:  "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name:   "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name:  "rear_right_wheel_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.0325
      sum_of_robot_center_projection_on_X_Y_axis: 1.0

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 6.0, 12.0, 18.0, 24.0, 30.0]

position_controllers:
  ros__parameters:
    joints:
      - camera_joint
      - camera_frame_joint
